### ISSUE TITLE
计算机图书分类问题

### ISSUE THREAD

**Issue by misakar** [gwuhaolin/ShuXun#1]
问题描述：计算机图书分类里出现几本生物书和物理书。
环境：我的手机是安卓的，书循是刚推出时的版本。

**Comment by gwuhaolin** [comment]
是没有加载完还是一直都那样显示？
最近更新你很多代码你再去看看，如果还是这样截个图看看。

**Comment by neo1218** [comment]
还是这样的，用我姐的iphone6也是这样
![书循](http://7xj431.com1.z0.glb.clouddn.com/shuxun.jpg)
那个《微生物学》。

**Comment by gwuhaolin** [comment]
哦，这是我的推荐算法的问题。目前的推荐算法还很简单，把和你同一个专业的同学上传的书推荐给查询的专业。有些同学上传了不是和自己专业相关的书。
我已经添加了用户行为数据收集模块，正在收集用户行为数据。
以后会用机器学习做专业的推荐算法。

**Comment by neo1218** [comment]
好的，我明白了，Thks!
